"""Embed admitright-students.csv in students-data.js so index.html works when opened from disk.

Phone and email are left out: universities must never see student contact details.

Run after regenerating the CSV:  python3 admitright/data/build_students_js.py
"""

import csv
import io
import json
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "admitright-students.csv"
OUT = HERE / "students-data.js"
DROP = {"phone", "email"}

with SRC.open(newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fields = [c for c in reader.fieldnames if c not in DROP]
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=fields, extrasaction="ignore", lineterminator="\n")
    writer.writeheader()
    count = 0
    for row in reader:
        writer.writerow(row)
        count += 1

OUT.write_text(
    "/* Generated by build_students_js.py from admitright-students.csv. Do not edit by hand. */\n"
    "window.ADMITRIGHT_STUDENTS_CSV = " + json.dumps(buf.getvalue()) + ";\n",
    encoding="utf-8",
)
print(f"Wrote {count} students to {OUT.name}")
